Refaktorisering af _regn.py
SDFIdk/FIRE pull request #691
Opened 2023-03-22 18:50 UTC by s176531

Så har jeg lavet en fuldstændig ren fork, som burde være identisk med SDFIdk/FIRE, bortset fra ændringer i _regn.py

2023-03-23 14:17 UTC, busstoptaktik requested changes
Der er lige et par småting og en enkelt lidt større med en lang kommentar, men overordnet ser det godt ud!

2023-03-23 14:17 UTC, busstoptaktik commented on fire/cli/niv/_regn.py
> +    arbejdssæt = np.array(arbejdssæt)
Det her med at håndtere dataelementer som nummererede søjler er ikke supergodt for kodens læselighed: Et NumPy-array er fornuftigt når alle elementer er ensfortolkede (altså som elementer i en matrix), men som du benytter det her mister vi overblikket over meningen med det enkelte dataelement.

Det er ikke det helt store problem her nede i funktionen selv, hvor de variabelnavne der skrives ind i arrayet giver tilstrækkelig hinting til at koden er læselig, men oppe i det kaldende program er den returnerede identitetsinformation reduceret til en stak indekstal, som ikke giver nogen information  om hvad det er man piller ud af den pågældende søjle i arrayet. **Der bliver det meget nemt at komme til at trække information fra en forkert søjle, hvilket så er meget vanskeligt at fejlfinde.**

I *ad hoc* tilfælde er løsningen at returnere en `list[dict]`, hvor hvert element af listen er en dict med sigende navne for hvert dataelement:

```python
arbejdselement = {'ny_kote': ny_kote, 'delta': Delta, 's.d.': sqrt(var), ...}
arbejdssæt.append(arbejdselement)
```

Men i mere *færdigbagte* løsninger er en `list[dataclass]`, med en til lejligheden nybagt dataclass, at foretrække, så man kan snakke om `arbejdselement.delta`, frem for `arbejdssæt[i, 7]`, eller `arbejdselement["delta"]`.

Her befinder vi os nok på kanten mellem *ad hoc* og *færdigbagt*, så om det er det ene eller det andet, der er løsningen, må være en smagssag. Men hvis du kigger op i den kaldende kode, hvor de returnerede data pakkes ud og anvendes, og forestiller dig hvad der skal til hvis vi en dag ændrer lidt på datamodellen, så tror jeg du vil kunne se at den af dine efterfølgere, der kommer til at sidde med den opgave, vil takke dig for at du droppede "magiske søjlenumre".

2023-03-23 14:17 UTC, busstoptaktik commented on fire/cli/niv/_regn.py
> +def skriv_gama(
`skriv_gama_inputfil(...)`

2023-03-27 06:26 UTC, s176531 commented on fire/cli/niv/_regn.py
> +) -> Tuple[list[str], list[float], list[float], Timestamp]:
Jeg kan godt lave det om til at være med småt, men som jeg læser PEP guiden, bør man anvende types fra `typing` biblioteket, såsom `Tuple`, `List` osv. til type hinting i funktioner/klasser/... i stedet for deres modstykke man anvender til at definere typen af variable i selve programmet.

2023-04-18 09:45 UTC, merged

2023-04-18 09:47 UTC, busstoptaktik commented
Jeg har squash-merget denne, da første commit i vid udstrækning blev overskrevet af andet, så den samlede ændring giver bedre mening end de to separate commits.