Punktsamling 3: Tilføj nye niv-underkommandoer til håndtering af punktsamlinger og tidsserier
SDFIdk/FIRE pull request #775
Opened 2024-09-27 12:59 UTC by krebslw

2024-09-30 10:13 UTC, kbevers requested changes

2024-09-30 10:13 UTC, kbevers commented on fire/cli/niv/punktsamling.py
> +    tidsserie, brug: ``fire niv XXXXX``
Har "XXXX" særlig mening? Eller skal man erstatte det med noget? I så fald, hvad?

2024-09-30 10:13 UTC, kbevers commented on fire/cli/niv/punktsamling.py
> +    Punktet angives med ``ident`` og punktsamlingens angives med ``punktsamlingsid``
"... og punktsamlingens *id* angives med ..." ?

2024-09-30 12:14 UTC, krebslw commented on fire/cli/niv/__init__.py
> +    """
Du har ret, det ved man ikke, men det er heller ikke nødvendigt at vide. Kan godt se at der er noget med formuleringen i docstringen som skal være mere tydelig omkring dette.

Denne funktion er lavet så det er muligt at fremsøge et punkt ud fra dets jessennr, hvilket jeg tidligere har oprettet issuet #754 på.  

Et alternatvit fix ville måske være at lade `hent_punkter` returnere en sorteret liste af matches, baseret på prioriteten defineret i klassen Ident:
```
class Ident:
    class IdentType(enum.Enum):
        GI = 1
        GNSS = 2
        LANDSNR = 3
        JESSEN = 4
        STATION = 5
        EKSTERN = 6
        DIVERSE = 7
        REFGEO = 8
        UKENDT = 9
        KORTUUID = 10
...
```
og så i `hent_punkter` sige (gammel/nuværende kode udkommenteret)
```
...
            result = (
                # self.session.query(Punkt)
                self.session.query(Punkt, PunktInformation)
...

# return result
return [p for p, _ in sorted(result, key = lambda result: Ident(result[1]))]
```
På denne måde vil `hent_punkt` ikke længere returnere det, i forespørgslen, "først fundne" punkt, men i stedet returnere det punkt som blev matchet på den højst prioriterede Ident.

Måske vil denne ændring føre til for meget unødvendig sortering. I så fald kan jeg enten lave et input til `hent_punkter` som bare kunne hedde `sorter: bool = False` hvor man kan vælge hvordan `hent_punkter` skal opføre sig.

2024-09-30 12:46 UTC, krebslw commented on fire/cli/niv/punktsamling.py
> +    valider_jessenpunkt(jessenpunkt)
Ja, det eneste den gør, er at tjekke om det punkt som brugeren har angivet som jessenpunkt også har et jessennummer. Hvis ikke, smides en fejl, og ellers sker der ikke noget.

2024-09-30 12:58 UTC, kbevers commented on fire/cli/niv/__init__.py
> +    """
Hvis funktionen skal hedder "hent_jessenpunkt" bør man enten få et jessenpunkt eller ingenting. Så jeg ville justere logikken til at returnere `None` hvis ikke der findes et jessenpunkt i opslaget. Eneste sted du bruger funktionen gør du sådan her

```
    try:
        jessenpunkt = hent_jessenpunkt(jessenpunkt_ident)
    except NoResultFound:
        fire.cli.print(
            f"FEJL: Kunne ikke finde Jessenpunktet {jessenpunkt_ident} i databasen!",
            fg="white",
            bg="red",
            bold=True,
        )
        raise SystemExit(1)
```

hvilket så kan justeres til 

```
    jessenpunkt = hent_jessenpunkt(jessenpunkt_ident)
    if not jessenpunkt:
        fire.cli.print(
            f"FEJL: Kunne ikke finde Jessenpunktet {jessenpunkt_ident} i databasen!",
            fg="white",
            bg="red",
            bold=True,
        )
        raise SystemExit(1)
```

Mht den egentlige problemstilling i #754, så kan vi måske i stedet udelade opslag på REFGEO ID'er fremadrettet. Det er ikke særligt relevant at kunne længere.

2024-09-30 13:00 UTC, kbevers commented on fire/cli/niv/punktsamling.py
> +    valider_jessenpunkt(jessenpunkt)
Jeg studsede over den flere gange. Det er lidt svært at se hvad man skal forvente der sker uden at læse koden til funktionen. Det må kunne klares med et simpelt navneskifte, fx til `afbryd_hvis_ugyldigt_jessenpunkt()`. Så er det mere tydeligt hvad der sker i tilfælde af punktet ikke dur til noget.

2024-09-30 13:07 UTC, krebslw commented on fire/cli/niv/punktsamling.py
> +        fire niv opret-punktsamling SAG --jessenpunkt 81005 --punkter "SKEJ,RDIO,BUDP"
Byttet ud til RDO1. Har skiftet jessenpunktet til 81022 som også ligger i nærheden. 81005 ligger i Gedser :D

2024-09-30 13:24 UTC, kbevers commented on fire/cli/niv/punktsamling.py
> +    tidsserie, brug: ``fire niv XXXXX``
Det må vi se som tiden går. Hvis det viser sig at behovet er der må vi gøre det muligt. Indtil da er det fint bare at skrive i dokumentationen at man kun kan tilføje nye koter til tidsserier. Så jeg synes altså at du skal fjerne bemærkningen på linje 779-780.

2024-09-30 13:24 UTC, krebslw commented on fire/cli/niv/punktsamling.py
> +        punktsamlinger = fire.cli.firedb.hent_alle_punktsamlinger()
Ja, bruger begge scenarier i "ilæg-punktsamlinger". For hver af de nye/redigerede punktsamlinger "PS", tjekkes om PS overlapper med nogle af de andre punktsamlinger som er ved at blive ilagt, og dernæst om PS overlapper med nogle af de punktsamlinger som allerede ligger i databasen.

2024-09-30 13:24 UTC, kbevers commented on fire/cli/niv/punktsamling.py
> +        fire niv opret-punktsamling SAG --jessenpunkt 81005 --punkter "SKEJ,RDIO,BUDP"
Super - Så slipper du får bedrevidende kommentarer om det ;)

2024-09-30 13:34 UTC, krebslw commented on fire/cli/niv/punktsamling.py
> +        formål="I henter smør!",
Det en Rick and morty reference!
![You+pass+butter](https://github.com/user-attachments/assets/a8b0d71d-f063-41d5-b7f7-7348cbe34e23)

Som jeg også har skrevet i docstring til "opret-punktsamling":
```
Tidsserier oprettes med default-formålet: "Giv os et formål!". Punktsamlinger oprettes
med default-formålet: "I henter smør!". Det anbefales et rette disse til noget mere passende.
```

Men det er bare en mærkelig pladsholder som oprettes i regnearket, så brugeren husker at ændre det til noget mere sigende inden det lægges i databasen. Ellers tænkter jeg der kommer til at være mange punktsamlinger/tidsserier med et tomt formålsfelt.

2024-09-30 13:37 UTC, krebslw commented on fire/cli/niv/punktsamling.py
> +def rediger_punktsamling(
Har faktisk også lavet det som en metode på `PunktSamling`. Kunne ikke beslutte mig og endte med at gøre det sådan her. Der er ingen grund til at det ikke kan være en metode, så hvis du synes, så laver jeg det bare om.

2024-09-30 13:49 UTC, kbevers commented on fire/cli/niv/punktsamling.py
> +        formål="I henter smør!",
Den kendte jeg ikke lige ;)

Nå, hvor sjovt det end er at skrive den slags finurlige referencer, så har de det med at stå i vejen når det kommer til den faktiske brug af programmet. Hvis der i stedet står "<Beskriv formål her>" eller lign. er det nemt for en bruger at forstå hvad der skal ske, hvorimod smørsætningen vist giver anledning til flere spørgsmål end svar. Spørgsmål der skal besvares hver gang en ny skal lære at bruge programmet.

Jeg tror med fordel du kan tvinge brugeren til at tage stilling til formålet. Ting man ikke behøver ændre på har det med at forblive uændrede.

2024-09-30 14:35 UTC, krebslw commented on fire/cli/niv/punktsamling.py
> +        formål="I henter smør!",
Ok! Lader formålet være tomt i excel arket og smider fejl hvis det ikke er udfyldt når man forsøger at lægge i databasen :)

2024-10-01 07:30 UTC, kbevers commented on fire/cli/niv/__init__.py
> +    """
> Derfor jeg mente at funktionens navn skal laves om så man ikke misforstår det. :)

Det er i hvert fald en nem løsning på problemet.

2024-10-01 09:03 UTC, kbevers commented on fire/cli/niv/__init__.py
> +    """
Refgeo id'er udelades nu i `FireDB.hent_punkt()`, jf https://github.com/SDFIdk/FIRE/pull/776

2024-10-01 11:26 UTC, krebslw commented on fire/cli/niv/punktsamling.py
> +) -> dict[list]:
Har lavet denne om, så den returnerer 3 sets i stedet for en dict med 3 lister i. Lavet typehintet om til `tuple[set[str], set[str], set[str]]` for at afspejle dette

2024-10-01 11:49 UTC, krebslw commented on fire/cli/niv/punktsamling.py
> +    punkter_fjernes: list[Punkt] = [],
Har besluttet at slette denne funktion. Den samlede egentlig bare de to `føj_punkter...` og `fjern_punkter...` funktioner i én, og havde tænkt det kunne være smart på et tidsspunkt. Men bruger den ikke nogen steder, og synes ikke længere den er så smart. Men godt at vide det med tomme lister som default! Der er sikkert par tilfælde rundt omkring jeg ikke har fanget, men prøver at være opmærksom på det.

2024-10-02 07:55 UTC, krebslw commented on fire/cli/niv/punktsamling.py
> +def føj_punkter_til_punktsamling(
er lavet som metode med [03b8846](https://github.com/SDFIdk/FIRE/pull/775/commits/03b8846e071c6d89b2327ffdeef220855d6f4ecf)

2024-10-02 07:56 UTC, krebslw commented on fire/cli/niv/punktsamling.py
> +    valider_jessenpunkt(jessenpunkt)
har ændret navnet til `afbryd_hvis_ugyldigt_jessenpunkt()`

2024-10-02 07:57 UTC, krebslw commented on fire/cli/niv/punktsamling.py
> +def rediger_punktsamling(
er lavet som metode med [03b8846](https://github.com/SDFIdk/FIRE/pull/775/commits/03b8846e071c6d89b2327ffdeef220855d6f4ecf)

2024-10-02 07:58 UTC, krebslw commented on fire/cli/niv/punktsamling.py
> +def rediger_punktsamling(
har slettet denne her. Se min anden kommentar:

> Har besluttet at slette denne funktion. Den samlede egentlig bare de to føj_punkter... og fjern_punkter... funktioner i én, og havde tænkt det kunne være smart på et tidsspunkt. Men bruger den ikke nogen steder, og synes ikke længere den er så smart. Men godt at vide det med tomme lister som default! Der er sikkert par tilfælde rundt omkring jeg ikke har fanget, men prøver at være opmærksom på det.

2024-10-02 07:59 UTC, krebslw commented on fire/cli/niv/punktsamling.py
> +def fjern_punkter_fra_punktsamling(
er lavet som metode med [03b8846](https://github.com/SDFIdk/FIRE/pull/775/commits/03b8846e071c6d89b2327ffdeef220855d6f4ecf)

2024-10-02 08:00 UTC, kbevers approved these changes

2024-10-02 08:01 UTC, merged